name: Release
on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Download artifacts
        uses: rspack-contrib/rspack-toolchain/download-rspack-binding@main
        with:
          path: artifacts

      - name: List packages
        run: ls -R artifacts
        shell: bash
